<?php

/**
 * @file
 * The main Module Permissions module file.
 *
 * Module Permissions allows a subset of modules to be enabled/disabled.
 */

/**
 * Implements hook_help().
 */
function module_permissions_help($path, $arg) {
  switch ($path) {
    case 'admin/help#module_permissions':
      $output = '<p>' . t("Allow administrators to define a list of modules that can be managed by others.") . '</p>';

      return $output;

    case 'admin/modules/managed':
      $output = '<p>' . t("Please select modules for users with permission 'Administer managed modules' to enable/disable.") . '</p>';

      return $output;

    case 'admin/config/system/managed-modules':
      $output = '<p>' . t("Please select modules for users with permission 'Administer managed modules' to enable/disable.") . '</p>';

      return $output;

    case 'admin/config/system/managed-modules/protected':
      $output = '<p>' . t("Please select modules that users cannot disable and uninstall.") . '</p>';

      return $output;
  }
}

/**
 * Implements hook_hook_info().
 */
function module_permissions_hook_info() {
  $hooks = array(
    'module_permissions_access' => array(
      'group' => 'module_permissions',
    ),
    'module_permissions_restrict' => array(
      'group' => 'module_permissions',
    ),
  );

  return $hooks;
}

/**
 * Implements hook_module_implements_alter().
 */
function module_permissions_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter' || $hook == 'menu_alter' || $hook == 'system_info_alter') {
    $group = $implementations['module_permissions'];
    unset($implementations['module_permissions']);
    $implementations['module_permissions'] = $group;
  }
}

/**
 * Implements hook_permission().
 */
function module_permissions_permission() {
  return array(
    'administer module permissions' => array(
      'title' => t('Administer the list of modules that can be managed by others'),
      'description' => t('Add and remove modules from the managed module list.'),
      'restrict access' => TRUE,
    ),
    'administer managed modules' => array(
      'title' => t('Administer managed modules'),
      'description' => t('Enable and disable modules from the managed module list.'),
      'restrict access' => TRUE,
    ),
    'administer managed modules permissions' => array(
      'title' => t('Administer managed modules permissions'),
      'description' => t('Configure permissions for the modules that are in the managed modules list.'),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Implements hook_menu().
 */
function module_permissions_menu() {
  // Managed modules list path.
  $items['admin/modules/managed'] = array(
    'title' => 'Managed modules',
    'description' => 'Add/remove modules from the managed module list.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('module_permissions_form_managed_modules'),
    'access arguments' => array('administer module permissions'),
    'file' => 'includes/module_permissions.pages.inc',
  );

  // Managed modules config path.
  $items['admin/config/system/managed-modules'] = array(
    'title' => 'Module permissions',
    'description' => 'Administer the list of modules that can be managed by others',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('module_permissions_form_managed_modules'),
    'access arguments' => array('administer module permissions'),
    'file' => 'includes/module_permissions.pages.inc',
  );
  $items['admin/config/system/managed-modules/managed'] = array(
    'title' => 'Managed modules',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/config/system/managed-modules/protected'] = array(
    'title' => 'Protected modules',
    'description' => 'Administer settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('module_permissions_form_protected_modules'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/module_permissions.pages.inc',
    'weight' => 10,
  );
  $items['admin/config/system/managed-modules/config'] = array(
    'title' => 'Configuration',
    'description' => 'Administer settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('module_permissions_config'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'includes/module_permissions.admin.inc',
    'weight' => 20,
  );

  return $items;
}

/**
 * Implements hook_menu_alter().
 */
function module_permissions_menu_alter(&$items) {
  // System user permissions and role forms.
  if (isset($items['admin/people/permissions'])) {
    $items['admin/people/permissions']['access callback'] = 'module_permissions_access';
    $items['admin/people/permissions']['access arguments'] = array('user_admin_permissions');
  }
  // System modules list.
  if (isset($items['admin/modules'])) {
    $items['admin/modules']['access callback'] = 'module_permissions_access';
    $items['admin/modules']['access arguments'] = array('system_modules');
  }
  // System modules confirm.
  if (isset($items['admin/modules/list/confirm'])) {
    $items['admin/modules/list/confirm']['access callback'] = 'module_permissions_access';
    $items['admin/modules/list/confirm']['access arguments'] = array('system_modules');
  }
}

/**
 * Provide a menu access callback.
 *
 * @see module_permissions_menu_alter()
 */
function module_permissions_access($op = 'system_modules', $account = NULL) {
  $access = &drupal_static(__FUNCTION__, array());

  $account = !empty($account) ? $account : $GLOBALS['user'];
  // Statically cache access by user account ID, and operation.
  $cid = $account->uid . ':' . $op;

  if (!isset($access[$cid])) {
    // Return FALSE by default.
    $access[$cid] = FALSE;

    // User #1 has all privileges:
    if ($account->uid == 1) {
      $access[$cid] = TRUE;

      return $access[$cid];
    }

    // Provide access hook for other modules.
    $access_results = module_invoke_all('module_permissions_access', $op, $account);

    if (in_array(FALSE, $access_results, TRUE)) {
      $access[$cid] = FALSE;

      return $access[$cid];
    }
    elseif (in_array(TRUE, $access_results, TRUE)) {
      $access[$cid] = TRUE;

      return $access[$cid];
    }

    // Check OP.
    if ($op == 'system_modules') {
      // Perform basic permission checks first.
      if (user_access('administer modules', $account)) {
        $access[$cid] = TRUE;

        return $access[$cid];
      }
      // Module permissions permission settings.
      if (user_access('administer managed modules', $account)) {
        $access[$cid] = TRUE;

        return $access[$cid];
      }
    }
    elseif ($op == 'user_admin_permissions') {
      // Perform basic permission checks first.
      if (user_access('administer permissions', $account)) {
        $access[$cid] = TRUE;

        return $access[$cid];
      }
      // Module permissions permission settings.
      if (user_access('administer managed modules permissions', $account) && user_access('administer managed modules', $account)) {
        $access[$cid] = TRUE;

        return $access[$cid];
      }
    }
  }

  return $access[$cid];
}

/**
 * Provide a restrict status check callback.
 *
 * @see module_permissions_form_alter()
 */
function module_permissions_restrict($op = 'system_modules', $account = NULL) {
  $restrict = &drupal_static(__FUNCTION__, array());

  $account = !empty($account) ? $account : $GLOBALS['user'];
  // Statically cache access by user account ID, and operation.
  $cid = $account->uid . ':' . $op;

  if (!isset($restrict[$cid])) {
    // Return TRUE by default.
    $restrict[$cid] = TRUE;

    // User #1 has all privileges:
    if ($account->uid == 1) {
      $restrict[$cid] = FALSE;

      return $restrict[$cid];
    }

    // Provide access hook for other modules.
    $restrict_results = module_invoke_all('module_permissions_restrict', $op, $account);

    if (in_array(TRUE, $restrict_results, TRUE)) {
      $restrict[$cid] = TRUE;

      return $restrict[$cid];
    }
    elseif (in_array(FALSE, $restrict_results, TRUE)) {
      $restrict[$cid] = FALSE;

      return $restrict[$cid];
    }

    // Check OP.
    if ($op == 'system_modules') {
      // Perform basic permission checks first.
      if (user_access('administer modules', $account)) {
        $restrict[$cid] = FALSE;

        return $restrict[$cid];
      }
      // Module permissions permission settings.
      if (user_access('administer managed modules', $account)) {
        $restrict[$cid] = TRUE;

        return $restrict[$cid];
      }
    }
    elseif ($op == 'user_admin_permissions') {
      // Perform basic permission checks first.
      if (user_access('administer permissions', $account)) {
        $restrict[$cid] = FALSE;

        return $restrict[$cid];
      }
      // Module permissions permission settings.
      if (user_access('administer managed modules permissions', $account) && user_access('administer managed modules', $account)) {
        $restrict[$cid] = TRUE;

        return $restrict[$cid];
      }
    }
  }

  return $restrict[$cid];
}

/**
 * Implements hook_form_alter().
 */
function module_permissions_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'system_modules':
    case 'user_admin_permissions':
      if (module_permissions_restrict($form_id)) {
        module_permissions_form_handler($form, 'module_permissions_form_' . $form_id . '_handler');
      }
      break;
  }
}

/**
 * Form alter handler callback.
 */
function module_permissions_form_handler(&$form, $callback = '') {
  // Load module inc file.
  module_load_include('inc', 'module_permissions', 'includes/module_permissions.forms');

  if (!empty($callback) && function_exists($callback)) {
    $callback($form);
    // Add logs submit callback.
    $form["#submit"][] = 'module_permissions_logs_submit';
  }
}

/**
 * Implements hook_system_info_alter().
 */
function module_permissions_system_info_alter(&$info, $file, $type) {
  // Limit type module.
  if ($type == 'module') {
    $protected_modules = module_permissions_load_protected_modules();
    if (isset($protected_modules[$file->name])) {
      // Protect this module.
      $info['required'] = TRUE;
      $info['explanation'] = t('This module is required and protected in current site');
    }
  }
}

/**
 * Get managed modules list.
 */
function module_permissions_load_managed_modules() {
  $managed_modules = &drupal_static(__FUNCTION__);

  if (!isset($managed_modules)) {
    $managed_modules = variable_get('module_permissions_managed_modules', array());
    $managed_modules = array_flip($managed_modules);
    // Remove module permissions from list.
    if (isset($managed_modules['module_permissions'])) {
      unset($managed_modules['module_permissions']);
    }
  }

  return $managed_modules;
}

/**
 * Get protected modules list.
 */
function module_permissions_load_protected_modules() {
  $protected_modules = &drupal_static(__FUNCTION__);

  if (!isset($protected_modules)) {
    $protected_modules = variable_get('module_permissions_protected_modules', array());
    $protected_modules = array_flip($protected_modules);
    // Remove module permissions from list.
    if (isset($protected_modules['module_permissions'])) {
      unset($protected_modules['module_permissions']);
    }
  }

  return $protected_modules;
}

/**
 * Implements hook_theme().
 */
function module_permissions_theme() {
  return array(
    'module_permissions_managed_modules_list' => array(
      'render element' => 'form',
      'file' => 'includes/module_permissions.theme.inc',
    ),
  );
}
