<?php

/**
 * @file
 * Contains module_permissions.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function module_permissions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the module_permissions module.
    case 'help.page.module_permissions':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Protects a site with the managed blacklist of modules, permissions and paths.') . '</p>';
      return $output;

    default:
  }
}
