<?php

/**
 * @file
 * Contains module_permissions.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function module_permissions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the module_permissions module.
    case 'help.page.module_permissions':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allow administrators to define a subset of modules to be managed by others') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function module_permissions_theme() {
  return [
    'module_permissions' => [
      'render element' => 'children',
    ],
  ];
}
